### ISSUE TITLE
ModuleNotFoundError: No module named 'past'

### ISSUE THREAD

**Issue by koen-dejonghe** [pbloem/former#1]
fix: `pip install future`

**Comment by pbloem** [comment]
This happens if you run python 2, right (or maybe anything below 3.7)? I've added some version information to the readme, plus your fix.

**Comment by koen-dejonghe** [comment]
I was using Python 3.7.4.
Thanks for the great blog and code, btw.

**Comment by pbloem** [comment]
That's odd. I don't get this even with 3.6... let's see if other people run into this problem.

**Comment by koen-dejonghe** [comment]
ok, so here's what I did:

```
conda create env --name former
conda activate former
pip install torch tb-nightly tqdm numpy torchtext
python experiments/classify.py
```
That's when I got the error.
I'm a Scala guy, and bizar things happen when I work with python.

**Comment by pbloem** [comment]
Yep, just reproduced. Full stacktrace:

```
Traceback (most recent call last):
  File "experiments/classify.py", line 16, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/Users/Peter/anaconda/envs/former/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 6, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "/Users/Peter/anaconda/envs/former/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 18, in <module>
    from ._convert_np import make_np
  File "/Users/Peter/anaconda/envs/former/lib/python3.7/site-packages/torch/utils/tensorboard/_convert_np.py", line 12, in <module>
    from caffe2.python import workspace
  File "/Users/Peter/anaconda/envs/former/lib/python3.7/site-packages/caffe2/python/workspace.py", line 15, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```

For now, importing ```future``` seems like a quick fix. I'll try to see later if there's a better solution.

**Comment by xanderladd** [comment]
It's weird how you can solve an issue with the past using the future
