### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by Cybernetic1** [pbloem/former#25]
$ python experiments/classify.py 

Traceback (most recent call last):
  File "experiments/classify.py", line 1, in <module>
    import former
  File "/home/yky/miniconda3/envs/former/lib/python3.7/site-packages/former/__init__.py", line 1, in <module>
    from .modules import SelfAttention, SelfAttentionWide, TransformerBlock, SelfAttentionRelative, SelfAttentionNarrow
  File "/home/yky/miniconda3/envs/former/lib/python3.7/site-packages/former/modules.py", line 1, in <module>
    from .util import mask_, d, slice_diag
ModuleNotFoundError: No module named 'former.util'

**Comment by jalotra** [comment]
Did you do `pip install -e .` ?

**Comment by Glinttsd** [comment]
same error here
