### ISSUE TITLE
ModuleNotFoundError: No module named 'past'

### ISSUE THREAD

**Issue by jjong2ya** [pbloem/former#9]
I am practicing pytorch and got an error as follows.

Traceback (most recent call last):
  File "D:/Programing/tensorboardtest.py", line 1, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\jjong\AppData\Roaming\Python\Python36\site-packages\torch\utils\tensorboard\__init__.py", line 6, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "C:\Users\jjong\AppData\Roaming\Python\Python36\site-packages\torch\utils\tensorboard\writer.py", line 18, in <module>
    from ._convert_np import make_np
  File "C:\Users\jjong\AppData\Roaming\Python\Python36\site-packages\torch\utils\tensorboard\_convert_np.py", line 12, in <module>
    from caffe2.python import workspace
  File "C:\Users\jjong\AppData\Roaming\Python\Python36\site-packages\caffe2\python\workspace.py", line 15, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'

Can any expert help me to solve?

**Comment by pbloem** [comment]
This happens occasionally with particular versions of python (not sure about the details). Try running
`pip install future`

**Comment by jjong2ya** [comment]
I did "pip install future" and it is installed, I guess.

**Comment by pbloem** [comment]
Did it fix the problem?

**Comment by jjong2ya** [comment]
No. It doesn't work.

**Comment by pbloem** [comment]
In that case I recommend you install [anaconda](https://www.anaconda.com/), and create a clean [virtual environment](https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/) to run the code. See the README.md for instructions on setting up such an environment when anaconda is installed.
